trigger:
- main

pool:
  name: "Default"

variables: 
  ACR_URL: "nhannguyenarc.azurecr.io"
  IMAGE_NAME: "frontend"
  IMAGE_TAG: "v1.$(Build.BuildId)"

stages:
  - stage: "build_image"
    displayName: "Build image"
    jobs:
      - job: "build_image"
        displayName: "Build frontend image"
        steps:
          - script: docker build -t $(ACR_URL)/$(IMAGE_NAME):$(IMAGE_TAG) .
  - stage: "push_image"
    displayName: "Push image"
    jobs:
      - job: "login"
        displayName: "Login to ACR"
        variables:
        - group: "az-credentials"
        steps:
          - script: echo $(ACR_PASSWORD) | docker login -u $(ACR_USERNAME) --password-stdin $(ACR_URL)
      - job: "push_image"
        displayName: "Push frontend image"
        dependsOn: "login"
        steps:
          - script: docker push $(ACR_URL)/$(IMAGE_NAME):$(IMAGE_TAG)
  - stage: "cleanup"
    displayName: "Cleanup"
    jobs:
      - job: "cleanup"
        displayName: "Cleanup image on agent"
        steps:
          - script: docker rmi $(ACR_URL)/$(IMAGE_NAME):$(IMAGE_TAG)
